name: BPfold
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - conda-forge
  - https://conda.rosettacommons.org
  - bioconda
dependencies:
  - pytorch=2.0.1=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - fastai=2.7.12=pyhd8ed1ab_0
  - yaml=0.2.5=h7b6447c_0
  - einops=0.7.0=pyhd8ed1ab_1
  - scikit-learn=1.3.0=py38h1128e8f_0
  - pip:
      - torchmetrics==1.0.3
      - tqdm==4.66.1
      - pyyaml==6.0.1
      - scikit-image==0.21.0
      - scipy==1.10.1
prefix: /public2/home/heqinzhu/miniconda3/envs/BPfold
